version: "3.8"

services:
  service-suppliers-nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - 8080:80
    depends_on:
      - php-fpm
      - mysql

  php-fpm:
    image: maxrollundev/php-fpm-dev-8.0
    volumes:
      - ./:/var/www/app
    environment:
      APP_ENV: dev

  php-openapi-generator:
    image: maxrollundev/php-openapi-generator:8.0
    volumes:
      - ./:/var/www/app
  mysql:
    image: mariadb:10.4
    volumes:
      - "./data/db:/var/lib/mysql"
    ports:
       - "3307:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=butler
      - MYSQL_USER=superAdminSecret
      - MYSQL_PASSWORD=root